### ISSUE TITLE
Program detection section

### ISSUE THREAD

**Issue by Robbedoes24** [vives-project-xp/MusicLightTiles#12]
Create a program to detect the presence of something/someone using the controller and the detection methode.

**Comment by Robbedoes24** [comment]
Added initial PlatformIO project to detect branch

**Comment by RubenBelligh** [comment]
I've watched videos on how to program with arduino. The reason for this is that I have never programmed with Arduino.

**Comment by RubenBelligh** [comment]
I programmed the detection. The detection allows pin 16 to connect to the ground.

**Comment by RubenBelligh** [comment]
I programmed a button to turn off the tiles. It is connected to pin 17.

**Comment by RubenBelligh** [comment]
I have made a flowchart of my program. In that chart you can see easily what it does.

**Comment by Robbedoes24** [comment]
Merged feature detect into develop
