### ISSUE TITLE
Program lighting section

### ISSUE THREAD

**Issue by Robbedoes24** [vives-project-xp/MusicLightTiles#13]
Create a program to adjust the lighting using the controller and the lighting solution.

**Comment by Robbedoes24** [comment]
Added initial PlatformIO project to light branch

**Comment by LucaClrk** [comment]
# First phase of the code

Today, I finished the initial code for the LED strip. I used the Adafruit NeoPixel library, which proved to be the best choice for our WS2814 RGBW LED strip. Initially, I conducted some tests to explore the capabilities of this LED strip. During testing, we discovered that the LED strip is divided into segments of 6 LEDs each. As a result, we cannot control each LED individually, but we can control each segment as desired. For one tile, we needed 16 segments, which corresponds to approximately 1.6 meters—the required length for a single tile.

I am aware that the LED strip will eventually be controlled by a signal sent via MQTT . I will receive an array through MQTT that will dictate which segments should light up and their respective colors. For testing, I created a 2D array named "arrayPixel[16][4]". This array represents 16 segments and 4 colors, suitable for an RGBW LED strip, including red, blue, green, and a white LED for additional brightness.

Next, I implemented a for loop to iterate over this array. The for loop traverses all the segments and determines the colors to be displayed. Allow me to illustrate this with the following screenshots:

### The Array
![image](https://github.com/vives-project-xp/MusicLightTiles/assets/90068844/c80cd310-8571-4136-a971-5e8cf216dab7)
This is the array I used for my testing. In the subsequent phase, this array will be transmitted via MQTT.

### The For Loop
![image](https://github.com/vives-project-xp/MusicLightTiles/assets/90068844/94d9f6c4-533f-4c09-be19-c53a0c6cd4df)
Here, you can observe the for loop iterating over "NUMPIXELS," which is equal to 16, as declared above the setup. It represents the number of segments used. Additionally, you can see the different colors [0, 1, 2, 3], later defined as red, white, green, and blue. Finally, I specify that the LEDs will operate at a brightness level of 50%.

**Comment by LucaClrk** [comment]
# Backup Code

As mentioned in my previous comment, the array will be sent through MQTT. However, in case MQTT is not fast enough and the lights start flickering, I have created a backup code with hard-coded lighting patterns. I am using a button as the detection method for this backup code. When the button is activated, the lighting will turn on and remain in that state. When I deactivate the button by pressing it again, the lights will all turn red. Currently, the lights are static, but in the future, I would like to add effects to the lighting. This backup code serves as a fail-safe.

### Button Activated
![image](https://github.com/vives-project-xp/MusicLightTiles/assets/90068844/57a3cd6f-a4f2-49c0-99d9-d6debd0c7ba0)

In this section, I code how the button is activated. I achieve this by comparing the current state of the button with the state before that current state. This is how I determine if the button is active or not, and it will remain in that state. The colors used here are the same as in the previous program.

### Button Deactivated
![image](https://github.com/vives-project-xp/MusicLightTiles/assets/90068844/93e07a08-8dcf-430c-9369-56e730402130)

This section consists of a simple `else` structure that uses the array to turn all the LEDs red. There is a small delay to eliminate any residual effects from the button. In the future, this delay may be removed.

**Comment by Robbedoes24** [comment]
Merged feature light into develop
