### ISSUE TITLE
Create websocket api

### ISSUE THREAD

**Issue by Robbedoes24** [vives-project-xp/MusicLightTiles#32]
Create a websocket api to interface with mqtt for later use.

**Comment by LucaClrk** [comment]
# Websocket 
The scrummaster asked me to learn how to work with Websocket. So I started reading and watching information about Websocket and learned that it makes a connection between a user and a server in real-time. This communiction is very fast and can be used in things like multiplayer gaming. 
## Websocket Programming
I started coding to learn Websocket. To establish a server I use javascript. You can also code it in other languages but javascript seems to be the go to language for this. I used Postman to check this connection. Here I could send messages to the server and receive the messages I put in the code.
## Explaining the code
This is the server side of Websocket. Here the is code explained in comments. First we include the 'ws' library by typing 'require('ws')' .Next we create the server and say on which port it will be working. Next we code all the basics to set up a simple server, I won't go into detail.
![image](https://github.com/vives-project-xp/MusicLightTiles/assets/90068844/4f05e592-f081-4aa2-a474-d7bcc80cdf93)
Next we will talk about the client side. Here you can send messages to the server. Here we setup the server and send a message as confirmation if it worked. 
![image](https://github.com/vives-project-xp/MusicLightTiles/assets/90068844/3f8b2599-8ea3-4963-9de1-82d881930828)
Here we send a message when the server is disconnected and when there is an error.
![image](https://github.com/vives-project-xp/MusicLightTiles/assets/90068844/33deb558-8f38-41b8-a036-d5ac2ca5050f)
With this command we can send messages to the server. Here we put a simple 'Hello, server!'.
![image](https://github.com/vives-project-xp/MusicLightTiles/assets/90068844/5aea5045-689f-4b5b-859a-53c5713c5267)

**Comment by Robbedoes24** [comment]
Websocket api has been integrated inside the control script.
