### ISSUE TITLE
Search for music and sound effects for audio section

### ISSUE THREAD

**Issue by Robbedoes24** [vives-project-xp/MusicLightTiles#33]
Create a list of (free to use) music and sound effects to be played by the speakers on the tiles.

**Comment by RubenBelligh** [comment]
We looked up music for the project. It's divided into 5 topics:
1. Movies
2. Classical music
3. POP music
4. Piano music
5. Funny sounds

**Comment by Robbedoes24** [comment]
New categories:
- Animals
- Gaming
- Memes
- Instruments
- TV and Movies
- Music

**Comment by Robbedoes24** [comment]
There is enough music
