### ISSUE TITLE
Add project documentation

### ISSUE THREAD

**Issue by Robbedoes24** [vives-project-xp/MusicLightTiles#40]
Add documentation about every aspect of the project.

**Comment by RubenBelligh** [comment]
I have made a document with some explanation about the project. In it I have given a summary of what the project entails, how it works, how the detection works, how the audio works and what you could do with it in the future.In it I have given a summary of what the project entails, how it works, how the detection works, how the audio works and what you could do with it in the future.

**Comment by RubenBelligh** [comment]
I made a manual for our project. This describes how you can put the project together and get a working product.

**Comment by RubenBelligh** [comment]
I  made a powerpoint for the presentation.

**Comment by Robbedoes24** [comment]
The project documentation can be found in the [README](https://github.com/vives-project-xp/MusicLightTiles) and the [wiki](https://github.com/vives-project-xp/MusicLightTiles/wiki).
