### ISSUE TITLE
Create test script

### ISSUE THREAD

**Issue by Robbedoes24** [vives-project-xp/MusicLightTiles#42]
### Files:
The files can be placed in a `testing` folder in the root directory of the repo.
- .env script for secrets (mqqt- host, port, username, password)
- copy.env (copy of .env, because .env should not be pushed to github)
- main.py (the script, using python)
- ... more if necessary

### Program Flow (from a user perspective)
1. Ask user for topic (ask again if incorrect)
2. Display all possible tiles to test (example: 1 - ABE64FHF616, 2 - 846ZFFG45 etc... )
3. Ask user for tile selection (one of the previous tiles, or multiple [extra])
4. Loop the following:
    - Run each possible command (change every pixel color, play audio, change volume, reboot, etc)
    - Ask user for visual confirmation (for every command run, no by default)
6. List everything that has been tested, the confirmation and a `pass` or `fail`
7. Ask the user if they want to test another device (yes or no) and run again if necessary

### Notes: 
- The program flow above is just what the user should experience, so don't forget about thing like connecting to mqtt where no user input is required
- If a command is send and an invalid responds is received, the tile still fails (even if there is visual confirmation)

**Comment by RubenBelligh** [comment]
I created a test script for the project. It tests the tiles by sending them various commands and then receives a visual confirmation.

**Comment by RubenBelligh** [comment]
I continued working on the script because it was not yet completely in order.

**Comment by RubenBelligh** [comment]
Debuggen of the code

**Comment by LucaClrk** [comment]
# First code
I have attempted to make code to be able to test the tiles. I have used python to make a connection with MQTT and send commands and read the tiles.

## Code
### MQTT Settings
![MQTTSettings](https://github.com/vives-project-xp/MusicLightTiles/assets/90068844/a6ccaffc-a478-4042-8b26-bd7036a2aefa)
Here I make sure I have the MQTT settings right so I can make a connection with it. For now I am only subscribed to TILE1. I still have to figure out how to connect to all active tiles.

### Using topics
![sendingfunctions](https://github.com/vives-project-xp/MusicLightTiles/assets/90068844/7499a40c-1e09-4f1c-a3d8-48dfb3f10599)

Here I subscribe to the topics I need to test the tile. I will test the audio, light and system. These are the subtopics of the command subtopic. I also subscribed to the presence subtopic. This will read if the tile is active or not.
Next I have programmed functions for the audio, light and system. 
![subscribemqtt](https://github.com/vives-project-xp/MusicLightTiles/assets/90068844/a0026a37-43e1-4459-9ed3-f426fe842554)

Here I send the commands to MQTT to test the tiles.

## Conclusion
This is my code untill now. I have not gotten further as things are starting to get more complicated.

**Comment by LucaClrk** [comment]
# Code Upgrade
I have upgraded my code. To look at the right code you need to click "tile_select.py".
Now I can choose which tile I choose. You do need to choose the tile from a list of available tiles. These available tiles are hardcoded and are not read from the MQTT broker. I am still searching how to do this.

![availabletiles](https://github.com/vives-project-xp/MusicLightTiles/assets/90068844/ae09a442-4701-4c73-87ad-a658623a1d8f)

This is the list of tiles you can choose from.
After choosing a tile all commands will be sent to this tile and I will also read information from it.

**Comment by Robbedoes24** [comment]
Test script is done.
