### ISSUE TITLE
Create electrical diagrams for individual sections and prototype

### ISSUE THREAD

**Issue by Robbedoes24** [vives-project-xp/MusicLightTiles#9]
Create electrical diagrams for the following sections:

- [x] Audio
- [x] Lighting
- [x] Detection
- [x] Control and communication

And a combined diagram for the prototype.

**Comment by LucaClrk** [comment]
Schema van ledstrip circuit gemaakt. We maken gebruik van een ESP32, WS2814 en een supply. Er kan ook nog een capaciteit gebruikt worden tussen de 24V en de GND maar dit is net noodzakelijk.

**Comment by RubenBelligh** [comment]
I made an electrical diagram of the detection system. This is connected to our microcontroller the ESP32.

**Comment by Robbedoes24** [comment]
I combined the electrical diagrams into 1 file, made a combined diagram with all sections and cleaned up the individual diagrams with wire colores and images of the components.
